# Generated by Django 6.0.2 on 2026-04-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_activitylog_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='map_layout',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_occupied',
        ),
        migrations.RemoveField(
            model_name='room',
            name='map_element_id',
        ),
        migrations.AddField(
            model_name='floor',
            name='name',
            field=models.CharField(default='Floor', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='position_index',
            field=models.IntegerField(default=1, help_text='Order on map (1-16)'),
            preserve_default=False,
        ),
    ]
