# Generated by Django 6.0.2 on 2026-05-01 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_floor_map_layout_remove_room_is_occupied_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['number']},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='room',
            name='position_index',
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.CharField(blank=True, help_text='Comma-separated: wifi, study_table, wardrobe, ac', max_length=200),
        ),
        migrations.AddField(
            model_name='room',
            name='attached_washroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_female_block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='position',
            field=models.CharField(choices=[('top', 'Top Row'), ('bottom', 'Bottom Row')], default='top', help_text='Visual row in the floor map', max_length=6),
        ),
        migrations.AddField(
            model_name='room',
            name='price_per_semester',
            field=models.DecimalField(decimal_places=2, default=45000, max_digits=10),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double Sharing'), ('triple', 'Triple Sharing')], default='double', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='login.room')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'room')},
            },
        ),
        migrations.DeleteModel(
            name='RoomApplication',
        ),
    ]
